In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
# one hot representation 
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3448, 9047, 3345, 3422],
 [3448, 9047, 3345, 4182],
 [3448, 2296, 3345, 2273],
 [9480, 3600, 663, 8170, 6119],
 [9480, 3600, 663, 8170, 597],
 [3351, 3448, 759, 3345, 8682],
 [3121, 8786, 5350, 8170]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8 
embedded_docs = pad_sequences(one_hot_repr , padding='pre' , maxlen= sent_length)
embedded_docs

array([[   0,    0,    0,    0, 3448, 9047, 3345, 3422],
       [   0,    0,    0,    0, 3448, 9047, 3345, 4182],
       [   0,    0,    0,    0, 3448, 2296, 3345, 2273],
       [   0,    0,    0, 9480, 3600,  663, 8170, 6119],
       [   0,    0,    0, 9480, 3600,  663, 8170,  597],
       [   0,    0,    0, 3351, 3448,  759, 3345, 8682],
       [   0,    0,    0,    0, 3121, 8786, 5350, 8170]])

In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 360ms/step


array([[[ 2.83587910e-02,  4.61663119e-02, -4.97989766e-02,
         -1.46720558e-03,  1.49540789e-02, -2.71352418e-02,
          3.42055447e-02,  3.01152579e-02, -6.81088120e-03,
          1.90638378e-03],
        [ 2.83587910e-02,  4.61663119e-02, -4.97989766e-02,
         -1.46720558e-03,  1.49540789e-02, -2.71352418e-02,
          3.42055447e-02,  3.01152579e-02, -6.81088120e-03,
          1.90638378e-03],
        [ 2.83587910e-02,  4.61663119e-02, -4.97989766e-02,
         -1.46720558e-03,  1.49540789e-02, -2.71352418e-02,
          3.42055447e-02,  3.01152579e-02, -6.81088120e-03,
          1.90638378e-03],
        [ 2.83587910e-02,  4.61663119e-02, -4.97989766e-02,
         -1.46720558e-03,  1.49540789e-02, -2.71352418e-02,
          3.42055447e-02,  3.01152579e-02, -6.81088120e-03,
          1.90638378e-03],
        [-3.66818905e-02, -1.67374015e-02,  1.24972351e-02,
         -1.06494203e-02,  4.20243479e-02,  1.63704418e-02,
          6.91439956e-03, -3.27610373e-02,  4.487990

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 3448, 9047, 3345, 3422])

In [14]:
model.predict(np.array([embedded_docs[0]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step


array([[[ 0.02835879,  0.04616631, -0.04979898, -0.00146721,
          0.01495408, -0.02713524,  0.03420554,  0.03011526,
         -0.00681088,  0.00190638],
        [ 0.02835879,  0.04616631, -0.04979898, -0.00146721,
          0.01495408, -0.02713524,  0.03420554,  0.03011526,
         -0.00681088,  0.00190638],
        [ 0.02835879,  0.04616631, -0.04979898, -0.00146721,
          0.01495408, -0.02713524,  0.03420554,  0.03011526,
         -0.00681088,  0.00190638],
        [ 0.02835879,  0.04616631, -0.04979898, -0.00146721,
          0.01495408, -0.02713524,  0.03420554,  0.03011526,
         -0.00681088,  0.00190638],
        [-0.03668189, -0.0167374 ,  0.01249724, -0.01064942,
          0.04202435,  0.01637044,  0.0069144 , -0.03276104,
          0.0448799 , -0.02823755],
        [ 0.04836606,  0.0210191 ,  0.03830684, -0.04277955,
          0.01892254,  0.03556136, -0.03154869, -0.0243293 ,
         -0.02346603,  0.04932876],
        [ 0.01452905,  0.02792383,  0.03602436,  0.0

In [15]:
model.predict(embedded_docs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


array([[[ 2.83587910e-02,  4.61663119e-02, -4.97989766e-02,
         -1.46720558e-03,  1.49540789e-02, -2.71352418e-02,
          3.42055447e-02,  3.01152579e-02, -6.81088120e-03,
          1.90638378e-03],
        [ 2.83587910e-02,  4.61663119e-02, -4.97989766e-02,
         -1.46720558e-03,  1.49540789e-02, -2.71352418e-02,
          3.42055447e-02,  3.01152579e-02, -6.81088120e-03,
          1.90638378e-03],
        [ 2.83587910e-02,  4.61663119e-02, -4.97989766e-02,
         -1.46720558e-03,  1.49540789e-02, -2.71352418e-02,
          3.42055447e-02,  3.01152579e-02, -6.81088120e-03,
          1.90638378e-03],
        [ 2.83587910e-02,  4.61663119e-02, -4.97989766e-02,
         -1.46720558e-03,  1.49540789e-02, -2.71352418e-02,
          3.42055447e-02,  3.01152579e-02, -6.81088120e-03,
          1.90638378e-03],
        [-3.66818905e-02, -1.67374015e-02,  1.24972351e-02,
         -1.06494203e-02,  4.20243479e-02,  1.63704418e-02,
          6.91439956e-03, -3.27610373e-02,  4.487990